name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source control
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Quasar Build
        run: |
          rm -rf dist/
          npm install -g @quasar/cli yarn --force
          yarn install
          quasar build
