name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-to-s3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
      - name: Install yarn
      - run: npm install --global yarn
      - name: Install quasar
      - run: yarn global add @quasar/cli
      - name: Quasar Build
      - run: quasar build
